In [1]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('../data/lead Scoring.csv')

In [6]:
df.shape

(9240, 37)

In [7]:
df.head()

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.5,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.0,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.0,...,No,Select,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.0,...,No,Select,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified

In [8]:
df.isnull().sum()

Prospect ID                                         0
Lead Number                                         0
Lead Origin                                         0
Lead Source                                        36
Do Not Email                                        0
Do Not Call                                         0
Converted                                           0
TotalVisits                                       137
Total Time Spent on Website                         0
Page Views Per Visit                              137
Last Activity                                     103
Country                                          2461
Specialization                                   1438
How did you hear about X Education               2207
What is your current occupation                  2690
What matters most to you in choosing a course    2709
Search                                              0
Magazine                                            0
Newspaper Article                                   0
X Education Forums                                  0
Newspaper                                           0
Digital Advertisement                               0
Through Recommendations                             0
Receive More Updates About Our Courses              0
Tags                                             3353
Lead Quality                                     4767
Update me on Supply Chain Content                   0
Get updates on DM Content                           0
Lead Profile                                     2709
City                                             1420
Asymmetrique Activity Index                      4218
Asymmetrique Profile Index                       4218
Asymmetrique Activity Score                      4218
Asymmetrique Profile Score                       4218
I agree to pay the amount through cheque            0
A free copy of Mastering The Interview              0
Last Notable Activity                               0
dtype: int64

# data cleaning

In [13]:
df_clean = df.copy()

In [14]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 9240 entries, 0 to 9239
Data columns (total 37 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Prospect ID                                    9240 non-null   str
 1   Lead Number                                    9240 non-null   int64
 2   Lead Origin                                    9240 non-null   str
 3   Lead Source                                    9204 non-null   str
 4   Do Not Email                                   9240 non-null   str
 5   Do Not Call                                    9240 non-null   str
 6   Converted                                      9240 non-null   int64
 7   TotalVisits                                    9103 non-null   float64
 8   Total Time Spent on Website                    9240 non-null   int64
 9   Page Views Per Visit                           9103 non-null   float64
 10  Last Activity                                  9137 non-null   str
 11  Country                                        6779 non-null   str
 12  Specialization                                 7802 non-null   str
 13  How did you hear about X Education             7033 non-null   str
 14  What is your current occupation                6550 non-null   str
 15  What matters most to you in choosing a course  6531 non-null   str
 16  Search                                         9240 non-null   str
 17  Magazine                                       9240 non-null   str
 18  Newspaper Article                              9240 non-null   str
 19  X Education Forums                             9240 non-null   str
 20  Newspaper                                      9240 non-null   str
 21  Digital Advertisement                          9240 non-null   str
 22  Through Recommendations                        9240 non-null   str
 23  Receive More Updates About Our Courses         9240 non-null   str
 24  Tags                                           5887 non-null   str
 25  Lead Quality                                   4473 non-null   str
 26  Update me on Supply Chain Content              9240 non-null   str
 27  Get updates on DM Content                      9240 non-null   str
 28  Lead Profile                                   6531 non-null   str
 29  City                                           7820 non-null   str
 30  Asymmetrique Activity Index                    5022 non-null   str
 31  Asymmetrique Profile Index                     5022 non-null   str
 32  Asymmetrique Activity Score                    5022 non-null   float64
 33  Asymmetrique Profile Score                     5022 non-null   float64
 34  I agree to pay the amount through cheque       9240 non-null   str
 35  A free copy of Mastering The Interview         9240 non-null   str
 36  Last Notable Activity                          9240 non-null   str
dtypes: float64(4), int64(3), str(30)
memory usage: 2.6 MB

In [15]:
# check for duplicate values
df_clean.duplicated().sum()

np.int64(0)

In [17]:
#handling placeholders/dummy values
df_clean.replace('Select',pd.NA,inplace=True)

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.00,...,No,NaN,NaN,02.Medium,02.Medium,15.0,15.0,No,No,Modified
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.50,...,No,NaN,NaN,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.00,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.00,...,No,NaN,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.00,...,No,NaN,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9235,19d6451e-fcd6-407c-b83b-48e1af805ea9,579564,Landing Page Submission,Direct Traffic,Yes,No,1,8.0,1845,2.67,...,No,Potential Lead,Mumbai,02.Medium,01.High,15.0,17.0,No,No,Email Marked Spam
9236,82a7005b-7196-4d56-95ce-a79f937a158d,579546,Landing Page Submission,Direct Traffic,No,No,0,2.0,238,2.00,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,19.0,No,Yes,SMS Sent
9237,aac550fe-a586-452d-8d3c-f1b62c94e02c,579545,Landing Page Submission,Direct Traffic,Yes,No,0,2.0,199,2.00,...,No,Potential Lead,Mumbai,02.Medium,01.High,13.0,20.0,No,Yes,SMS Sent
9238,5330a7d1-2f2b-4df4-85d6-64ca2f6b95b9,579538,Landing Page Submission,Google,No,No,1,3.0,499,3.00,...,No,NaN,Other Metro Cities,02.Medium,02.Medium,15.0,16.0,No,No,SMS Sent
9239,571b5c8e-a5b2-4d57-8574-f2ffb06fdeff,579533,Landing Page Submission,Direct Traffic,No,No,1,6.0,1279,3.00,...,No,Potential Lead,Other Cities,02.Medium,01.High,15.0,18.0,No,Yes,Modified

In [16]:
# check for unique values like ID
for col in df_clean.columns:
    print(col,"->",df_clean[col].nunique(),"/",len(df))

Prospect ID -> 9240 / 9240
Lead Number -> 9240 / 9240
Lead Origin -> 5 / 9240
Lead Source -> 21 / 9240
Do Not Email -> 2 / 9240
Do Not Call -> 2 / 9240
Converted -> 2 / 9240
TotalVisits -> 41 / 9240
Total Time Spent on Website -> 1731 / 9240
Page Views Per Visit -> 114 / 9240
Last Activity -> 17 / 9240
Country -> 38 / 9240
Specialization -> 19 / 9240
How did you hear about X Education -> 10 / 9240
What is your current occupation -> 6 / 9240
What matters most to you in choosing a course -> 3 / 9240
Search -> 2 / 9240
Magazine -> 1 / 9240
Newspaper Article -> 2 / 9240
X Education Forums -> 2 / 9240
Newspaper -> 2 / 9240
Digital Advertisement -> 2 / 9240
Through Recommendations -> 2 / 9240
Receive More Updates About Our Courses -> 1 / 9240
Tags -> 26 / 9240
Lead Quality -> 5 / 9240
Update me on Supply Chain Content -> 1 / 9240
Get updates on DM Content -> 1 / 9240
Lead Profile -> 6 / 9240
City -> 7 / 9240
Asymmetrique Activity Index -> 3 / 9240
Asymmetrique Profile Index -> 3 / 9240
Asymmetrique Activity Score -> 12 / 9240
Asymmetrique Profile Score -> 10 / 9240
I agree to pay the amount through cheque -> 1 / 9240
A free copy of Mastering The Interview -> 2 / 9240
Last Notable Activity -> 16 / 9240

In [18]:
df_clean.drop(columns=['Prospect ID','Lead Number'],inplace=True)

In [19]:
constant_col=['I agree to pay the amount through cheque','Get updates on DM Content',
              'Update me on Supply Chain Content','Receive More Updates About Our Courses','Magazine']
df_clean.drop(columns=constant_col,inplace=True)

In [26]:
df_clean.shape

(9240, 23)

In [22]:
for col in ['A free copy of Mastering The Interview','Through Recommendations','Digital Advertisement','Newspaper',
            'X Education Forums','Newspaper Article','Search','Converted','Do Not Call','Do Not Email']:
    print(col)
    print(df_clean[col].value_counts(normalize=True))
    print( )

A free copy of Mastering The Interview
A free copy of Mastering The Interview
No     0.687446
Yes    0.312554
Name: proportion, dtype: float64

Through Recommendations
Through Recommendations
No     0.999242
Yes    0.000758
Name: proportion, dtype: float64

Digital Advertisement
Digital Advertisement
No     0.999567
Yes    0.000433
Name: proportion, dtype: float64

Newspaper
Newspaper
No     0.999892
Yes    0.000108
Name: proportion, dtype: float64

X Education Forums
X Education Forums
No     0.999892
Yes    0.000108
Name: proportion, dtype: float64

Newspaper Article
Newspaper Article
No     0.999784
Yes    0.000216
Name: proportion, dtype: float64

Search
Search
No     0.998485
Yes    0.001515
Name: proportion, dtype: float64

Converted
Converted
0    0.61461
1    0.38539
Name: proportion, dtype: float64

Do Not Call
Do Not Call
No     0.999784
Yes    0.000216
Name: proportion, dtype: float64

Do Not Email
Do Not Email
No     0.920563
Yes    0.079437
Name: proportion, dtype: float64

In [23]:
near_const_col=['Do Not Call','Search','Newspaper Article','X Education Forums','Newspaper','Digital Advertisement',
                'Through Recommendations',]
df_clean.drop(columns=near_const_col,inplace=True)

In [25]:
df_clean.shape

(9240, 23)

In [29]:
# handling null values

df_clean.isnull().sum().sort_values(ascending=False)

How did you hear about X Education               7250
Lead Profile                                     6855
Lead Quality                                     4767
Asymmetrique Activity Index                      4218
Asymmetrique Profile Score                       4218
Asymmetrique Profile Index                       4218
Asymmetrique Activity Score                      4218
City                                             3669
Specialization                                   3380
Tags                                             3353
What matters most to you in choosing a course    2709
What is your current occupation                  2690
Country                                          2461
TotalVisits                                       137
Page Views Per Visit                              137
Last Activity                                     103
Lead Source                                        36
Lead Origin                                         0
Do Not Email                                        0
Total Time Spent on Website                         0
Converted                                           0
A free copy of Mastering The Interview              0
Last Notable Activity                               0
dtype: int64

In [30]:
(df_clean.isnull().sum() / len(df_clean) * 100).sort_values(ascending=False)

How did you hear about X Education               78.463203
Lead Profile                                     74.188312
Lead Quality                                     51.590909
Asymmetrique Activity Index                      45.649351
Asymmetrique Profile Score                       45.649351
Asymmetrique Profile Index                       45.649351
Asymmetrique Activity Score                      45.649351
City                                             39.707792
Specialization                                   36.580087
Tags                                             36.287879
What matters most to you in choosing a course    29.318182
What is your current occupation                  29.112554
Country                                          26.634199
TotalVisits                                       1.482684
Page Views Per Visit                              1.482684
Last Activity                                     1.114719
Lead Source                                       0.389610
Lead Origin                                       0.000000
Do Not Email                                      0.000000
Total Time Spent on Website                       0.000000
Converted                                         0.000000
A free copy of Mastering The Interview            0.000000
Last Notable Activity                             0.000000
dtype: float64

In [33]:
leakage_and_high_missing = ['How did you hear about X Education', 'Lead Profile', 
                              'Lead Quality', 'Tags']

df_clean.drop(columns=leakage_and_high_missing, inplace=True)

In [36]:
df_clean.shape

(9240, 19)

In [39]:
cols_to_fill_categorical = ['City', 'Specialization', 'What matters most to you in choosing a course',
                              'What is your current occupation', 'Country',
                              'Asymmetrique Activity Index', 'Asymmetrique Profile Index']
for col in cols_to_fill_categorical:
    df_clean[col]=df_clean[col].fillna('Not Specified')

In [40]:
df_clean['Asymmetrique Activity Score'] = df_clean['Asymmetrique Activity Score'].fillna(
    df_clean['Asymmetrique Activity Score'].median())

df_clean['Asymmetrique Profile Score'] = df_clean['Asymmetrique Profile Score'].fillna(
    df_clean['Asymmetrique Profile Score'].median())

In [41]:
df_clean['TotalVisits'] = df_clean['TotalVisits'].fillna(df_clean['TotalVisits'].median())
df_clean['Page Views Per Visit'] = df_clean['Page Views Per Visit'].fillna(df_clean['Page Views Per Visit'].median())
df_clean['Last Activity'] = df_clean['Last Activity'].fillna(df_clean['Last Activity'].mode()[0])
df_clean['Lead Source'] = df_clean['Lead Source'].fillna(df_clean['Lead Source'].mode()[0])

In [42]:
df_clean.isnull().any()

Lead Origin                                      False
Lead Source                                      False
Do Not Email                                     False
Converted                                        False
TotalVisits                                      False
Total Time Spent on Website                      False
Page Views Per Visit                             False
Last Activity                                    False
Country                                          False
Specialization                                   False
What is your current occupation                  False
What matters most to you in choosing a course    False
City                                             False
Asymmetrique Activity Index                      False
Asymmetrique Profile Index                       False
Asymmetrique Activity Score                      False
Asymmetrique Profile Score                       False
A free copy of Mastering The Interview           False
Last Notable Activity                            False
dtype: bool

In [45]:
df_clean.isnull().sum().sum()

np.int64(0)

In [47]:
df_clean.shape

(9240, 19)

In [48]:
df_clean.isnull().sum().sum()

np.int64(0)

In [49]:
df_clean.head()

,Lead Origin,Lead Source,Do Not Email,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Country,Specialization,What is your current occupation,What matters most to you in choosing a course,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,A free copy of Mastering The Interview,Last Notable Activity
0,API,Olark Chat,No,0,0.0,0,0.0,Page Visited on Website,Not Specified,Not Specified,Unemployed,Better Career Prospects,Not Specified,02.Medium,02.Medium,15.0,15.0,No,Modified
1,API,Organic Search,No,0,5.0,674,2.5,Email Opened,India,Not Specified,Unemployed,Better Career Prospects,Not Specified,02.Medium,02.Medium,15.0,15.0,No,Email Opened
2,Landing Page Submission,Direct Traffic,No,1,2.0,1532,2.0,Email Opened,India,Business Administration,Student,Better Career Prospects,Mumbai,02.Medium,01.High,14.0,20.0,Yes,Email Opened
3,Landing Page Submission,Direct Traffic,No,0,1.0,305,1.0,Unreachable,India,Media and Advertising,Unemployed,Better Career Prospects,Mumbai,02.Medium,01.High,13.0,17.0,No,Modified
4,Landing Page Submission,Google,No,1,2.0,1428,1.0,Converted to Lead,India,Not Specified,Unemployed,Better Career Prospects,Mumbai,02.Medium,01.High,15.0,18.0,No,Modified